spring:
  profiles:
    active: local
  application.name: 'web-flux'

  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

management:
  endpoint:
    health:
      show-details: always